### ISSUE TITLE
Wouldn't applying an `Integrator.ofGreedy` not make sense?

### ISSUE THREAD

**Issue by ullenboom** [tginsberg/gatherers4j#57]
https://github.com/tginsberg/gatherers4j/blob/5b46f28bdefa0e977bec71a48c4ff0fb898cd395/src/main/java/com/ginsberg/gatherers4j/ReversingGatherer.java#L34

    @Override
    public Integrator<State<INPUT>, INPUT, INPUT> integrator() {
      return Integrator.ofGreedy( ( state, element, _ ) -> state.inputs.add(element) );
    }

**Comment by tginsberg** [comment]
Hi! Yes, very probably so. I have an item on my TODO list to go through and be more consistent about using Greedy and parallelizing where possible.

**Comment by tginsberg** [comment]
I implemented every integrator I could using `ofGreedy` and will ship it in 0.7.0. Thanks for the prod to do this!
